// ID de la hoja de cálculo y del formulario
const SPREADSHEET_ID = '17nygtbMiRWZLbRZRxkoCuz5DMdhYOpDlIs0XV4spF3w';
const FORM_ID = '1XYRdsOT619nHuCemyGSu5sIlWkKjeceFDb1p1zN8hFI';
const TG_TOKEN = '5817418058:AAEYWFzEN_NisLSoQku30Z07qbu3GgOXuos'; //TOKEN DEL BOT DE TELEGRAM
const TG_CHAT_ID = '-1002179069352'; //ID DEL CHAT PARA EL BOT DE TELEGRAM
const TG_CHAT_DIRECT = '1339900005'; //ID DEL CHAT DIRECTO DEL BOT
const TG_CHAT_COM = '-1002879478954'; // ID DEL CHAT PARA RECEPCION DE COMUNICACIONES
const TG_BUTTON_TRIGGER_KEYWORD = 'SOFICREDITOS';
const TG_BUTTON_OPTIONS = ['INCENTIVO', 'FALLO', 'RECOMPENSA'];
const TG_BUTTON_OFFSET_KEY = 'TG_BUTTON_CONTROL_OFFSET';
const TG_BUTTON_CALLBACK_PREFIX = 'BTN:';
const TG_BUTTON_LAST_UPDATE_KEY = 'TG_BUTTON_LAST_UPDATE_ID';
